Global:
  use_gpu: true
  epoch_num: 20
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_crnn/
  save_epoch_step: 5
  eval_batch_step: [0,2000]
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  use_visualdl: false
  character_dict_path: ppocr/utils/ic15_dict.txt
  max_text_length: 25

Optimizer:
  name: Adam
  lr:
    name: Cosine
    learning_rate: 0.001

Architecture:
  model_type: rec
  algorithm: CRNN
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
  Head:
    name: CTCHead
    fc_decay: 1e-4

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015_rec/
    label_file_list: ["./train_data/icdar2015_rec/train_label.txt"]
    transforms:
      - DecodeImage: {img_mode: BGR, channel_first: false}
      - RecAug: {}
      - CTCLabelEncode: {}
      - NormalizeImage: {scale: 1./255., mean: [0.5,0.5,0.5], std: [0.5,0.5,0.5]}
      - ToCHWImage: {}
      - KeepKeys: {keep_keys: ["image", "label", "length"]}

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015_rec/
    label_file_list: ["./train_data/icdar2015_rec/train_label.txt"]
    transforms:
      - DecodeImage: {img_mode: BGR, channel_first: false}
      - CTCLabelEncode: {}
      - NormalizeImage: {scale: 1./255., mean: [0.5,0.5,0.5], std: [0.5,0.5,0.5]}
      - ToCHWImage: {}
      - KeepKeys: {keep_keys: ["image", "label", "length"]}
